[project]
name = "valgrind-sarif-action"
version = "0.1.0"
description = "Translate Valgrind XML to SARIF"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "argparse>=1.4.0",
    "jschema-to-python>=1.2.3",
    "sarif-om>=1.0.4",
    "xmltodict>=0.14.2",
]
