name: SARIF Tester

on:
  - push

jobs:
  run_tests:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4.1.4

      - name: "Install dependencies"
        run: |
          sudo apt update && sudo apt install -y valgrind

      - name: "Compile tests"
        run: |
          gcc -g tests/test_invalid_free.c -o test_invalid_free
          gcc -g tests/test_invalid_read.c -o test_invalid_read
          gcc -g tests/test_invalid_write.c -o test_invalid_write
          gcc -g tests/test_no_free.c -o test_no_free
          gcc -g tests/test_realloc_zero.c -o test_realloc_zero
          gcc -g tests/test_unclosed_file_descriptor.c -o test_unclosed_file_descriptor

      - name: "Valgrind test_invalid_free run"
        run: | 
          valgrind \
          --track-origins=yes --read-var-info=yes --trace-children=yes \
          --show-leak-kinds=all --read-inline-info=yes --errors-for-leak-kinds=all \
          --expensive-definedness-checks=yes \
          --xml=yes --xml-file=valgrind-output.xml \
          ./test_invalid_free

      - name: "Valgrind test_invalid_free convert"
        uses: ./
        with:
          xml_input_file: "valgrind-output.xml"
          sarif_output_file: "valgrind-output.sarif"

      # - name: "Valgrind test_invalid_read"
      #   uses: ./
      #   with:
      #     binary_path: "./test_invalid_read"
      #     treat_error_as_warning: true

      # - name: "Valgrind test_invalid_write"
      #   uses: ./
      #   with:
      #     binary_path: "./test_invalid_write"
      #     treat_error_as_warning: true

      # - name: "Valgrind test_no_free"
      #   uses: ./
      #   with:
      #     binary_path: "./test_no_free"
      #     treat_error_as_warning: true

      # - name: "Valgrind test_realloc_zero"
      #   uses: ./
      #   with:
      #     binary_path: "./test_realloc_zero"
      #     treat_error_as_warning: true

      # - name: "Valgrind test_unclosed_file_descriptor"
      #   uses: ./
      #   with:
      #     binary_path: "./test_unclosed_file_descriptor"
      #     treat_error_as_warning: true
      - name: "Upload SARIF file"
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: valgrind-output.sarif
          category: valgrind
